FROM openjdk:17
COPY --from=builder build/libs/*.jar app.jar
# builder 이미지에서 build/libs/*.jar 파일을 app.jar로 복사

FROM openjdk:17 AS builder
VOLUME /tmp

COPY ./gradlew .
# gradlew 복사
COPY ./gradle gradle
# gradle 복사
COPY ./build.gradle .
# build.gradle 복사
COPY ./settings.gradle .
# settings.gradle 복사
COPY ./src src
# 웹 어플리케이션 소스 복사
RUN chmod +x ./gradlew
# gradlew 실행 권한 부여

# 불필요한 패키지 설치 제거 (필요 없으면)
RUN microdnf install findutils

RUN ./gradlew bootJar
# 실행 가능한 JAR 파일 생성

# 최종 이미지
FROM openjdk:17
COPY --from=builder build/libs/*.jar app.jar
# 빌더에서 생성된 JAR 파일을 복사

# RUN mkdir -p /var/log/spring-boot
# 로그 디렉토리 생성

EXPOSE 8080
# 컨테이너의 8080 포트를 외부로 노출

COPY wait-for-it.sh wait-for-it.sh
RUN chmod +x wait-for-it.sh
# wait-for-it.sh 스크립트 복사 및 실행 권한 부여

# wait-for-it.sh가 성공한 후 애플리케이션 실행
ENTRYPOINT ["./wait-for-it.sh", "mysqldb:3306", "-s", "-t", "100", "--", "java", "-Djava.security.egd=file:/dev/./urandom", "-jar", "/app.jar"]
