services:
  db:
    image: mysql:8.0
    container_name: mysqldb
    ports:
      - "3306:3306"
    env_file:
      - backend-secret.env
      
  backend:
    build:
      context: .
      dockerfile: Dockerfile-develop
    container_name: backend
    restart: always
    depends_on:
      - db
    env_file:
      - backend-secret.env
    ports:
      - "8080:8080"
    volumes:
      - .:/app
#      - ./logs:/var/log/spring-boot
