name: CI

on:
  push:
    branches:
      - 'fe/**'  # fe/로 시작하는 모든 브랜치에 대해 푸시 이벤트 트리거
  pull_request:
    branches:
      - main
      - develop

jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn build

      - name: Install serve package
        run: yarn add serve --dev

      - name: Run Lighthouse CI
        run: |
          npx serve -s dist -l 4173 &
          sleep 5
          lhci autorun --collect.url=http://localhost:4173 --collect.startServerCommand='' --collect.numberOfRuns=3
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
