name: CI

on:
  push:
    branches:
      - 'fe/**'  # fe/로 시작하는 모든 브랜치에 대해 푸시 이벤트 트리거
  pull_request:
    branches:
      - main
      - develop

jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: yarn && yarn add @lhci/cli@0.6.x
      - run: yarn build
      - run: yarn add serve --dev
      - run: lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}